---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      skip: true
      paths:
        - 'vars'

- name: Include OS-specific tasks
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      skip: true

- name: Set timezone in Linux like OS
  community.general.timezone:
    name: "{{ ntp_timezone }}"

- name: Ensure NTP is running and enabled as configured
  ansible.builtin.service:
    name: "{{ ntp_daemon }}"
    state: started
    enabled: true
  when: ntp_enabled | bool

- name: Ensure NTP is stopped and disabled as configured
  ansible.builtin.service:
    name: "{{ ntp_daemon }}"
    state: stopped
    enabled: false
  when: not (ntp_enabled | bool)

- name: Generate configuration file
  ansible.builtin.template:
    src: "{{ lookup('first_found', params) }}"
    dest: "/etc/{{ ntp_package }}.conf"
    mode: 0644
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.{{ ntp_package }}.conf.j2"
        - "{{ ansible_distribution }}.{{ ntp_package }}.conf.j2"
        - "{{ ansible_os_family }}.{{ ntp_package }}.conf.j2"
        - "{{ ntp_package }}.conf.j2"
      paths:
        - 'templates'
  tags: template-ntp-config
  notify: Restart ntp
