---
- name: Converge
  hosts: all
  become: yes

  pre_tasks:
    - name: Bootstrap ansible
      raw: test -e /usr/bin/python || test -e /usr/bin/python3 || test -e /usr/local/bin/python3 || (test -e /usr/bin/yum && sudo yum -y -qq install python3) || (test -e /usr/sbin/pkg && sudo env ASSUME_ALWAYS_YES=yes pkg update && sudo env ASSUME_ALWAYS_YES=yes pkg install python3)
      args:
        executable: /bin/sh
      #      debugger: always

  tasks:
    - name: "Include ansible-role-ntp"
      include_role:
        name: "ansible-role-ntp"
