---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu16
    image: ubuntu:xenial
  - name: ubuntu18
    image: ubuntu:bionic
  - name: ubuntu20
    image: ubuntu:focal
  - name: debian9
    image: debian:9
  - name: debian10
    image: debian:10
provisioner:
  name: ansible
verifier:
  name: ansible
